services:
  db:
    build: ./database
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - edhub_postgres_storage:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  edhub_postgres_storage:
